spring.datasource.url=jdbc:postgresql://localhost:5433/minotor_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Comma-separated list of your front-end origins
jwt.secret=change_me_to_a_strong_random_string

# Token lifetime in minutes
jwt.expiration-minutes=60

# Comma-separated list of your front-end origins
cors.allowed-origins=http://localhost:3000,https://your-frontend.com